services:
  - type: web
    name: onlinebanking-laravel
    env: php
    plan: free
    branch: main
    buildCommand: |
      composer install
      cp .env.example .env
      php artisan key:generate
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
